spring:
  application:
    name: lcx-ai-agent
  ai:
    dashscope:
      api-key: "sk-6264f2825a044d33a1bf4d238768237d"
      chat:
        options:
          model: qwen-turbo
#    mcp:
#      client:
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8127
#    mcp:
#      client:
#        sse:
#          connections:
#            imageSearch:
#              url: http://localhost:8127
#  datasource:
#    url: jdbc:postgresql://rm-cn-b8p4m1ifn0001yeo.rwlb.rds.aliyuncs.com/yu_ai_agent
#    username: my_user
#    password: licaixin060321@
#    ai:
#      vectorstore:
#        pgvector:
#          index-type: HNSW
#          dimensions: 1536
#          distance-type: COSINE_DISTANCE
#          max-document-batch-size: 10000
